[package]
name = "ping-pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = "1.3.3"
cosmwasm-std = "1.3.3"
cw-storage-plus = "1.1.0"
